[package]
name = "graph-git"
version = "0.1.0"
edition = "2021"
authors = ["Ralf Anton Beier <ralf_beier@me.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18.0"
neo4rs = "0.6.2"
tracing = "0.1.37"
